[package]
name = "rust"
version = "0.1.0"
authors = ["Patrick O'Brien <patrick.obrien@pob.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = "0.9.0-rc.1"
