on: [push]
name: Deploy_JS_Bot

jobs:
    env:
      working-directory: ./src/js/
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@master

        - name: 'Build the app'
          uses: actions/setup-node@v1
          working-directory: ${{ env.working-directory }}
          with:
            node-version: '14'
        - run: |
            yarn install --frozen-lockfile
            yarn run build
            touch .env
            echo 'BOT_TOKEN=${{ secrets.BOT_TOKEN }}' >> .env
            echo 'REILLY_ID=${{ secrets.REILLY_ID }}' >> .env
            echo 'GUILD_ID=${{ secrets.GUILD_ID }}' >> .env
            echo 'CHANNEL_ID=${{ secrets.CHANNEL_ID }}' >> .env
            echo 'REILLY_TIMEOUT_ROLE_ID=${{ secrets.REILLY_TIMEOUT_ROLE_ID }}' >> .env
            echo 'GOD_ID=${{ secrets.GOD_ID }}' >> .env

        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          working-directory: ${{ env.working-directory }}
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        - uses: azure/docker-login@v1
          working-directory: ${{ env.working-directory }}
          with:
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build . -t pobrien91/reillybot:${{ github.sha }}
            docker push pobrien91/reillybot:${{ github.sha }}

        - name: 'Deploy to Azure Container Instances'
          working-directory: ${{ env.working-directory }}
          uses: 'azure/aci-deploy@v1'
          with:
            resource-group: ${{ secrets.RESOURCE_GROUP }}
            dns-name-label: reillybot
            image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/pobrien91/reillybot:${{ github.sha }}
            registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            registry-username: ${{ secrets.REGISTRY_USERNAME }}
            registry-password: ${{ secrets.REGISTRY_PASSWORD }}
            name: reillybot-container
            location: 'east us'
