on: [push]
name: Linux_Container_Workflow

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@master

        - name: 'Build the app'
          uses: actions/setup-node@v1
          with:
            node-version: '14'
        - run: |
            yarn install --frozen-lockfile
            yarn run build
            echo 'BOT_TOKEN=${{ secrets.BOT_TOKEN }}\nREILLY_ID=${{ secrets.REILLY_ID }}\nGUILD_ID=${{ secrets.GUILD_ID }}\nCHANNEL_ID=${{ secrets.CHANNEL_ID }}\nREILLY_TIMEOUT_ROLE_ID=${{ secrets.REILLY_TIMEOUT_ROLE_ID }}' >> .env

        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        - uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}pobrien91/reillybot:${{ github.sha }}
            docker push pobrien91/reillybot:${{ github.sha }}

        - name: 'Deploy to Azure Container Instances'
          uses: 'azure/aci-deploy@v1'
          with:
            resource-group: ${{ secrets.RESOURCE_GROUP }}
            dns-name-label: reillybot
            image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/pobrien91/reillybot:${{ github.sha }}
            registry-username: ${{ secrets.REGISTRY_USERNAME }}
            registry-password: ${{ secrets.REGISTRY_PASSWORD }}
            name: reillybot-container
            location: 'east us'
