on: [push]
name: Deploy_Bot

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
      - name: "Checkout GitHub Action"
        uses: actions/checkout@master

      - name: "Build the app"
        uses: actions/setup-node@v1
        with:
          node-version: "14"
      - run: |
          yarn install --frozen-lockfile
          yarn run build
          touch .env
          echo 'BOT_TOKEN=${{ secrets.BOT_TOKEN }}' >> .env
          echo 'REILLY_ID=${{ secrets.REILLY_ID }}' >> .env
          echo 'GUILD_ID=${{ secrets.GUILD_ID }}' >> .env
          echo 'CHANNEL_ID=${{ secrets.CHANNEL_ID }}' >> .env
          echo 'REILLY_TIMEOUT_ROLE_ID=${{ secrets.REILLY_TIMEOUT_ROLE_ID }}' >> .env
          echo 'GOD_ID=${{ secrets.GOD_ID }}' >> .env
